#!/usr/bin/env python3
"""BlastRadius report renderer — phase 3 of the pipeline. Pure stdlib.

Consumes graph.json and renders the committed `blastradius.md` at the repo
root. Output is DETERMINISTIC: identical graph → byte-identical markdown
(no timestamps; the only volatile token is the commit hash on the header
line, which CI ignores when deciding whether the report changed).
"""

import argparse
import json
from collections import defaultdict
from pathlib import Path

TOP_HOTSPOTS = 20
TOP_SYMBOLS = 15
TOP_CLASS_ROWS = 15
MAX_CYCLES_SHOWN = 10
MAX_DIAGRAM_NODES = 14
CONCENTRATION_SHARE = 0.6  # one symbol carrying ≥60% of attributed radius

TIER_BADGE = {
    "critical": "🔴 critical",
    "high": "🟠 high",
    "medium": "🟡 medium",
    "low": "🟢 low",
    "none": "⚪ none",
}

# Per-tier node styling for the Mermaid diagram: (fill, stroke, text).
# Saturated fills with a matching darker border and contrasting text, so the
# nodes stay legible on BOTH GitHub light and dark backgrounds.
TIER_STYLE = {
    "critical": ("#e5484d", "#7f1d1d", "#ffffff"),
    "high":     ("#f2820a", "#8a4b06", "#ffffff"),
    "medium":   ("#f5d90a", "#7a6a00", "#2b2600"),
    "low":      ("#30a46c", "#125a38", "#ffffff"),
    "none":     ("#8b95a5", "#4b5563", "#ffffff"),
}


def _fmt_pct(p):
    return f"{p:.1f}%"


def _short(path, n=60):
    return path if len(path) <= n else "…" + path[-(n - 1):]


def _mermaid_id(i):
    return f"n{i}"


def _diagram_nodes(graph):
    """Top-N files by score with real dependents — the diagram's node set."""
    ranked = sorted(graph["files"].items(), key=lambda kv: (-kv[1]["score"], kv[0]))
    return [(rel, m) for rel, m in ranked if m["transitive"] > 0][:MAX_DIAGRAM_NODES]


def _mermaid_label(rel, m):
    """HTML label for a node: bold filename + blast-radius %. Escaped, and
    filenames are truncated so wide names don't blow out the layout."""
    name = rel.rsplit("/", 1)[-1]
    if len(name) > 26:
        name = name[:25] + "…"
    name = name.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return f"<b>{name}</b><br/>{m['pct']:.0f}%"


def render(graph: dict) -> str:
    files = graph["files"]
    n_files = graph["n_files"]
    res = graph["resolution"]
    hubs = set(graph["hubs"])

    ranked = sorted(files.items(), key=lambda kv: (-kv[1]["score"], kv[0]))
    hotspots = [(rel, m) for rel, m in ranked if m["transitive"] > 0][:TOP_HOTSPOTS]

    lines = []
    add = lines.append

    add("# 💥 BlastRadius Report")
    add("")
    commit = (graph.get("built_at_commit") or "unknown")[:12]
    add(f"> Generated by BlastRadius v{graph['tool_version']} at commit "
        f"`{commit}` — do not edit by hand; regenerate with "
        f"`python3 .claude/skills/blastradius/run.py`")
    add("")
    add("This report answers **\"what breaks if I change this?\"** for every "
        "file and class in the repo, from a statically-built, bidirectional "
        "dependency graph. No LLM, no server — deterministic analysis, "
        "committed here so the whole team (and coding agents) can read it.")
    add("")

    # ---------------- Overview ----------------
    add("## Overview")
    add("")
    total_imports = max(1, res["imports_total"])
    resolved_pct = 100.0 * res["resolved"] / total_imports
    add(f"| Files analyzed | Dependency edges | Imports resolved | Type-ref edges | Ambiguous (skipped, not guessed) |")
    add(f"|---:|---:|---:|---:|---:|")
    add(f"| {n_files} | {graph['n_edges']} | {res['resolved']}/{res['imports_total']} "
        f"({resolved_pct:.0f}%) | {res['type_ref_edges']} | {res['ambiguous_skipped']} |")
    add("")
    add("Edges are created **only** when an import or type reference resolves "
        "unambiguously to a repo file. External/unresolvable imports create no "
        "edge — this graph under-claims rather than lies.")
    add("")

    # ---------------- Tier distribution ----------------
    tier_counts = defaultdict(int)
    for _, m in files.items():
        tier_counts[m["tier"]] += 1
    add("## Risk tiers")
    add("")
    add("| Tier | Meaning | Files |")
    add("|---|---|---:|")
    add(f"| {TIER_BADGE['critical']} | ≥25% of repo depends on it | {tier_counts['critical']} |")
    add(f"| {TIER_BADGE['high']} | ≥10% | {tier_counts['high']} |")
    add(f"| {TIER_BADGE['medium']} | ≥3% | {tier_counts['medium']} |")
    add(f"| {TIER_BADGE['low']} | <3%, but depended on | {tier_counts['low']} |")
    add(f"| {TIER_BADGE['none']} | nothing depends on it | {tier_counts['none']} |")
    add("")

    # ---------------- Hotspots ----------------
    add("## Top hotspots — handle with care")
    add("")
    if not hotspots:
        add("_No internal dependencies detected._")
        add("")
    else:
        add("| # | File | Tier | Direct | Transitive | % of repo | Depth | Load-bearing symbols |")
        add("|--:|---|---|---:|---:|---:|---:|---|")
        for i, (rel, m) in enumerate(hotspots, 1):
            load_bearing = [s for s in m["symbols"] if s["attributed_direct"] > 0][:2]
            sym_txt = ", ".join(
                f"`{s['name']}` ({s['attributed_direct']})" for s in load_bearing
            ) or "—"
            hub_mark = " ⚠️hub" if rel in hubs else ""
            add(f"| {i} | `{_short(rel)}`{hub_mark} | {TIER_BADGE[m['tier']]} | "
                f"{m['direct']} | {m['transitive']} | {_fmt_pct(m['pct'])} | "
                f"{m['depth']} | {sym_txt} |")
        add("")

    # ---------------- Concentrated risk ----------------
    concentrated = []
    for rel, m in hotspots:
        attr_syms = [s for s in m["symbols"] if s["attributed_direct"] > 0]
        total_attr = sum(s["attributed_direct"] for s in attr_syms)
        if total_attr >= 3 and attr_syms:
            top = attr_syms[0]
            share = top["attributed_direct"] / total_attr
            if share >= CONCENTRATION_SHARE and len(m["symbols"]) > 1:
                concentrated.append((rel, m, top, share))
    if concentrated:
        add("## Concentrated risk — the file isn't the hotspot, one symbol is")
        add("")
        add("In these files, the blast radius flows through a single "
            "class/function. **Changes touching that symbol are the risky "
            "ones; edits elsewhere in the same file are much lower-risk.**")
        add("")
        add("| File | Load-bearing symbol | Carries | Its radius | Rest of file |")
        add("|---|---|---:|---:|---|")
        for rel, m, top, share in concentrated:
            add(f"| `{_short(rel)}` | `{top['name']}` ({top['kind']}, "
                f"L{top['line']}-{top['end_line']}) | {share:.0%} of attributed deps | "
                f"{_fmt_pct(top['pct'])} of repo | lower-risk |")
        add("")

    # ---------------- Load-bearing symbols ----------------
    all_syms = []
    for rel, m in files.items():
        for s in m["symbols"]:
            if s["attributed_direct"] > 0:
                all_syms.append((rel, s))
    all_syms.sort(key=lambda t: (-t[1]["attributed_direct"], -t[1]["transitive"], t[0], t[1]["line"]))
    if all_syms:
        add("## Most depended-on symbols")
        add("")
        add("| Symbol | Kind | Defined in | Direct dependents | Transitive | % of repo |")
        add("|---|---|---|---:|---:|---:|")
        for rel, s in all_syms[:TOP_SYMBOLS]:
            add(f"| `{s['name']}` | {s['kind']} | `{_short(rel, 50)}:{s['line']}` | "
                f"{s['attributed_direct']} | {s['transitive']} | {_fmt_pct(s['pct'])} |")
        add("")

    # ---------------- Hubs ----------------
    if graph["hubs"]:
        add(f"## Hubs (depended on by ≥{graph['hub_threshold']} files)")
        add("")
        add("Utility modules the whole repo leans on. Any change here needs "
            "extra review — but their ubiquity is usually by design.")
        add("")
        for rel in graph["hubs"]:
            m = files[rel]
            add(f"- `{rel}` — {m['direct']} direct dependents, "
                f"{_fmt_pct(m['pct'])} of repo transitively")
        add("")

    # ---------------- Cycles ----------------
    if graph["cycles"]:
        add("## Circular dependencies")
        add("")
        add("Files in a cycle share each other's full blast radius — a bug in "
            "any of them can propagate to all of them. Breaking these cycles "
            "shrinks the repo's blast surface.")
        add("")
        for cyc in graph["cycles"][:MAX_CYCLES_SHOWN]:
            shown = " → ".join(f"`{c}`" for c in cyc[:6])
            more = f" (+{len(cyc) - 6} more)" if len(cyc) > 6 else ""
            add(f"- {shown}{more}")
        if len(graph["cycles"]) > MAX_CYCLES_SHOWN:
            add(f"- _…and {len(graph['cycles']) - MAX_CYCLES_SHOWN} more cycles_")
        add("")

    # ---------------- Directory rollup ----------------
    dir_stats = defaultdict(lambda: {"files": 0, "score": 0.0, "top": ("", 0.0)})
    for rel, m in files.items():
        parts = rel.split("/")
        d = "/".join(parts[:2]) if len(parts) > 2 else (parts[0] if len(parts) > 1 else ".")
        st = dir_stats[d]
        st["files"] += 1
        st["score"] += m["score"]
        if m["pct"] > st["top"][1]:
            st["top"] = (rel, m["pct"])
    add("## By directory")
    add("")
    add("| Directory | Files | Riskiest file | Its radius |")
    add("|---|---:|---|---:|")
    for d in sorted(dir_stats, key=lambda k: (-dir_stats[k]["score"], k))[:15]:
        st = dir_stats[d]
        top_rel, top_pct = st["top"]
        top_txt = f"`{_short(top_rel, 45)}`" if top_rel else "—"
        add(f"| `{d}/` | {st['files']} | {top_txt} | {_fmt_pct(top_pct)} |")
    add("")

    # ---------------- Diagram ----------------
    diagram = _diagram_nodes(graph)
    node_ids = {rel: _mermaid_id(i) for i, (rel, _) in enumerate(diagram)}
    if diagram:
        add("## Dependency map")
        add("")
        add("Top hotspots, colored by risk tier; arrows point from a file to "
            "what it depends on (**A → B** means *A breaks if B breaks*). "
            "A dashed white outline marks a hub.")
        add("")
        add("```mermaid")
        add("%%{init: {'theme':'base','themeVariables':{"
            "'fontFamily':'ui-sans-serif,-apple-system,Segoe UI,Roboto,sans-serif',"
            "'fontSize':'13px','lineColor':'#8b93a1','primaryBorderColor':'#8b93a1'},"
            "'flowchart':{'curve':'basis','nodeSpacing':45,'rankSpacing':60}}}%%")
        add("flowchart TD")
        for rel, nid in node_ids.items():
            m = files[rel]
            add(f'    {nid}(["{_mermaid_label(rel, m)}"])')
        drawn = set()
        for e in graph["edges"]:
            src, dst = e["src"], e["dst"]
            if src in node_ids and dst in node_ids and (src, dst) not in drawn:
                drawn.add((src, dst))
                add(f"    {node_ids[src]} --> {node_ids[dst]}")
        # tier color classes
        for tier, (fill, stroke, text) in TIER_STYLE.items():
            members = [nid for rel, nid in node_ids.items()
                       if files[rel]["tier"] == tier]
            if members:
                add(f"    classDef {tier} fill:{fill},stroke:{stroke},"
                    f"stroke-width:1.5px,color:{text};")
                add(f"    class {','.join(members)} {tier};")
        # hub emphasis — dashed light outline layered over the tier fill
        hub_ids = [nid for rel, nid in node_ids.items() if rel in hubs]
        if hub_ids:
            add("    classDef hub stroke:#f5f7fa,stroke-width:2.5px,"
                "stroke-dasharray:4 3;")
            add(f"    class {','.join(hub_ids)} hub;")
        add("```")
        add("")

    # ---------------- Methodology ----------------
    add("---")
    add("")
    add("<details>")
    add("<summary><b>Methodology & limitations</b></summary>")
    add("")
    add("- **Edges**: path-aware import resolution (Python/JS), declared-package + "
        "type-name resolution (Java/Kotlin), uniqueness-gated type references "
        "(Swift). Ambiguous references are *skipped, never guessed*. In Swift, "
        "references to a local type whose name shadows a ubiquitous framework "
        "type (SwiftUI `Button`/`Section`, Foundation `Data`, …) are also "
        "skipped — the reference can't be told apart from the framework type.")
    add("- **Symbol attribution**: each edge records the symbols it enters a file "
        "through (imported names, referenced types). Whole-module imports can't "
        "be attributed and count conservatively against every symbol in the file.")
    add(f"- **Score**: transitive dependents with per-hop decay "
        f"(Σ 0.6^(depth−1)) — a direct importer matters more than one 4 hops away.")
    add("- **Static only**: runtime wiring (dependency injection, reflection, "
        "event buses, HTTP/RPC between services) is invisible to this analysis. "
        "Treat the radius as a *floor*, not a ceiling.")
    add("- Generated by [BlastRadius](https://github.com/rahulr85r/blastradius) — "
        "tree-sitter + pure-stdlib analysis; no LLM, no network, no server.")
    add("")
    add("</details>")
    add("")

    return "\n".join(lines)


def main():
    p = argparse.ArgumentParser(description="BlastRadius report renderer")
    p.add_argument("--graph", type=Path, required=True)
    p.add_argument("--out", type=Path, required=True)
    args = p.parse_args()
    with open(args.graph, encoding="utf-8") as f:
        graph = json.load(f)
    args.out.write_text(render(graph), encoding="utf-8")


if __name__ == "__main__":
    main()
